import Modal from "@/components/Modal";
import "./globals.css";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "To-do Trello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="bg-[#F5F6F8]">
          {children}
          <Modal />
        </body>
      </ClerkProvider>
    </html>
  );
}
